### PR TITLE
Add Formatter (spec + CI step)

### PR DESCRIPTION
**Pull request by svilupp**
Closes https://github.com/JuliaML/OpenAI.jl/issues/55

This PR introduces 3 changes:
- `.JuliaFormatter.toml` formatting spec set to [SciML formatting guidelines](https://domluna.github.io/JuliaFormatter.jl/dev/sciml_style/)
- CI step (last step) that fails if PR is not formatted (to maintain style over time)
- Minor update to CONTRIBUTING to reflect this change in the PR requirements

Why? It saves you time. You don't have to add spaces manually, you don't have to disabled your VSCode auto-formatter, etc. It all just works.

The code does not look pretty and sometimes it looks a bit suboptimal (too many lines), but it never impacts readability negatively.

Let me know what you think!

EDIT: the large amount of change is purely the effect of running the formatter. I haven't touched any files besides the ones outlined above.

### CODE REVIEW

**Comment by cpfiffer** [comment]
Can we bump this one?

**Comment by cpfiffer** [comment]
Seems like the failures here are due to not having an API key for the testing suite. I'd recommend we merge this in since the changes are cosmetic and the JuliaFormatter step seems appropriate.

**Comment by rory-linehan** [comment]
Happy to merge this as soon as the conflicts are resolved. I can resolve in the morning, almost kicked this illness

**Comment by svilupp** [comment]
Hey! Sorry to hear you were sick... Let me refresh it with Main -- it's a simple formatted, so it shouldn't take any effort.

**Pull request merged**
