### PR TITLE
Assistants API

### PR DESCRIPTION
**Pull request by cpfiffer**
This is a WIP draft to add API coverage for the [OpenAI Assistant](https://platform.openai.com/docs/api-reference/assistants) tooling.

This implements the bulk of the beta API, with the exception of the [File](https://platform.openai.com/docs/api-reference/files) endpoints. This requires a bigger effort than this PR.

We may wish to stash all this stuff in a submodule like `OpenAI.Assistants`, especially since there are so many API endpoints associated with the assistants.

I'm also addressing some formatting stuff inside the repo, since many of the function declarations are very wide and do not generally fit in most conventional editing panes. This is however not the primary focus of this PR and may not be complete. I'd prefer if we merged in #56 so that the formatting issues were addressed more thoroughly.

## API implementations

Assistants API to implement
- [X] Create assistant
- [X] Retrieve assistant
- [X] Modify assistant
- [X] Delete assistant
- [X] List assistants

Threads
- [x] Create thread
- [x] Retrieve thread
- [x] Modify thread
- [x] Delete thread

Messages
- [x] Create message
- [x] Retrieve message
- [x] Delete message
- [x] Modify message
- [x] List messages

Runs
- [x] Create run
- [x] Retrieve run
- [x] Modify run
- [x] List runs
- [x] cancel run

Will not be implemented in this PR:
- create thread and run
- Retrieve run step
- List run steps
- Submit tool outputs to run
- Create assistant file
- Retrieve assistant file
- Delete assistant file
- List assistant files
- Retrieve message file
- List message files

### CODE REVIEW

**Comment by cpfiffer** [comment]
As per #50, I'm going to leave anything that has to do with the Files API out of the PR.

**Comment by cpfiffer** [comment]
Okie dokie! We're now ready for a review. I added tests and such but we should be good to go here. All tests pass locally using my personal API key.

**Comment by cpfiffer** [comment]
@rory-linehan could we merge this one or do a review? The tests fail due to not having and API key, but they pass locally on my machine.

**Comment by rory-linehan** [comment]
Looks good to me! Sorry, I've been traveling for the past couple weeks.

**Comment by rory-linehan** [comment]
Tests seem to fail on my side, and after merge.. I'm familiarizing myself with the Assistants API to figure out what's going on. Do they still pass for you locally? The failure I'm seeing is:

```
{
  "error": {
    "message": "Cannot update run with status 'in_progress'.",
    "type": "invalid_request_error",
    "param": null,
    "code": null
  }
}
```

**Pull request merged**
